name: Publish to NPM
on:
  push:
    branches:
      - 'dev-*'
  release:
    types: [created]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Setup Node
        uses: actions/setup-node@v2
        with:
          node-version: '22.x'
          registry-url: 'https://registry.npmjs.org'
          scope: '@weerly_3'
      - name: Install dependencies and build 🔧
        run: npm i && npm run build
      - name: Publish package on NPM 📦
        run: cd dist && npm publish
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}


